/**
 * Database types - Auto-generated by Supabase CLI
 *
 * To regenerate, run:
 * supabase gen types typescript --project-id ymkdslderliwjuipeisz > src/types/database/index.ts
 *
 * This is a placeholder until the database schema is created.
 */

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          role: 'client' | 'mechanic' | 'admin'
          first_name: string | null
          last_name: string | null
          phone: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          role?: 'client' | 'mechanic' | 'admin'
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          avatar_url?: string | null
        }
        Update: {
          email?: string
          role?: 'client' | 'mechanic' | 'admin'
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          avatar_url?: string | null
        }
      }
      vehicles: {
        Row: {
          id: string
          client_id: string
          plate: string | null
          make: string
          model: string
          year: number
          vin: string | null
          mileage: number | null
          fuel_type: 'essence' | 'diesel' | 'electrique' | 'hybride' | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          plate?: string | null
          make: string
          model: string
          year: number
          vin?: string | null
          mileage?: number | null
          fuel_type?: 'essence' | 'diesel' | 'electrique' | 'hybride' | null
        }
        Update: {
          plate?: string | null
          make?: string
          model?: string
          year?: number
          vin?: string | null
          mileage?: number | null
          fuel_type?: 'essence' | 'diesel' | 'electrique' | 'hybride' | null
        }
      }
      services: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          category: string
          price_from: number
          duration_minutes: number
          icon: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          category: string
          price_from: number
          duration_minutes: number
          icon?: string | null
          is_active?: boolean
        }
        Update: {
          name?: string
          slug?: string
          description?: string | null
          category?: string
          price_from?: number
          duration_minutes?: number
          icon?: string | null
          is_active?: boolean
        }
      }
      appointments: {
        Row: {
          id: string
          client_id: string
          mechanic_id: string | null
          vehicle_id: string
          service_id: string
          scheduled_at: string
          address: string
          city: string
          zip_code: string
          status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled'
          price: number
          duration: number
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          mechanic_id?: string | null
          vehicle_id: string
          service_id: string
          scheduled_at: string
          address: string
          city: string
          zip_code: string
          status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled'
          price: number
          duration: number
          notes?: string | null
        }
        Update: {
          mechanic_id?: string | null
          scheduled_at?: string
          address?: string
          city?: string
          zip_code?: string
          status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled'
          price?: number
          duration?: number
          notes?: string | null
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: 'client' | 'mechanic' | 'admin'
      appointment_status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled'
      fuel_type: 'essence' | 'diesel' | 'electrique' | 'hybride'
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
